/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Aynur Cemre Aka
 */
public class AllSongs extends javax.swing.JFrame {
    Db db;
    ResultSet rs;
    Customer c;
    /**
     * Creates new form AllSongs
     */
    public AllSongs() 
    {
        db= new Db();
        initComponents();
        loadTableList();
    }
    public AllSongs(Customer c) 
    {
        this.c=c;
        db= new Db();
        initComponents();
        loadTableList();
    }   
    public final void loadTableList()
    {
        String[] tableColName = {"Name","Genre","Artist","Path"}; 
        DefaultTableModel mt = (DefaultTableModel) songList.getModel();
        mt.setColumnIdentifiers(tableColName);
        db.getInfo("system",songList, mt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        songList = new javax.swing.JTable();
        deleteSongButton = new javax.swing.JButton();
        addSongButton = new javax.swing.JButton();
        addplaylistButton = new javax.swing.JButton();
        mainmenuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("All Songs");

        jPanel2.setBackground(new java.awt.Color(32, 33, 35));
        jPanel2.setPreferredSize(new java.awt.Dimension(715, 588));

        songList.setBackground(new java.awt.Color(204, 204, 255));
        songList.setForeground(new java.awt.Color(255, 255, 255));
        songList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        songList.setGridColor(new java.awt.Color(32, 38, 74));
        songList.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(songList);
        if (songList.getColumnModel().getColumnCount() > 0) {
            songList.getColumnModel().getColumn(0).setHeaderValue("Title 1");
            songList.getColumnModel().getColumn(1).setHeaderValue("Title 2");
            songList.getColumnModel().getColumn(2).setHeaderValue("Title 3");
            songList.getColumnModel().getColumn(3).setHeaderValue("Title 4");
        }

        deleteSongButton.setBackground(new java.awt.Color(126, 87, 194));
        deleteSongButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteSongButton.setText("Delete Song");
        deleteSongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSongButtonActionPerformed(evt);
            }
        });

        addSongButton.setBackground(new java.awt.Color(126, 87, 194));
        addSongButton.setForeground(new java.awt.Color(255, 255, 255));
        addSongButton.setText("Add Song");
        addSongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSongButtonActionPerformed(evt);
            }
        });

        addplaylistButton.setBackground(new java.awt.Color(126, 87, 194));
        addplaylistButton.setForeground(new java.awt.Color(255, 255, 255));
        addplaylistButton.setText("Add to the Playlist");
        addplaylistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addplaylistButtonActionPerformed(evt);
            }
        });

        mainmenuButton.setBackground(new java.awt.Color(126, 87, 194));
        mainmenuButton.setForeground(new java.awt.Color(255, 255, 255));
        mainmenuButton.setText("Main Menu");
        mainmenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(deleteSongButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(addSongButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(addplaylistButton)
                .addGap(65, 65, 65)
                .addComponent(mainmenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteSongButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addSongButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addplaylistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainmenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainmenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenuButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_mainmenuButtonActionPerformed

    private void addplaylistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addplaylistButtonActionPerformed
        String name="";
        String genre=songList.getModel().getValueAt(songList.getSelectedRow(),1).toString();
        String artist=songList.getModel().getValueAt(songList.getSelectedRow(),2).toString();
        String path=songList.getModel().getValueAt(songList.getSelectedRow(),3).toString();
        try{
            name=songList.getModel().getValueAt(songList.getSelectedRow(),0).toString();
            db.addSong(c.getUserName(),name,genre,artist,path);
        }catch(ArrayIndexOutOfBoundsException e)
        {
            JOptionPane.showMessageDialog(AllSongs.this, "No song is selected!");
            return;
        }
        catch(Exception s){
            JOptionPane.showMessageDialog(AllSongs.this, "You already have: "+name);
            return;
        }
        JOptionPane.showMessageDialog(AllSongs.this, "Successfully added to playlist: "+name);
        new AllSongs(c).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addplaylistButtonActionPerformed

    private void addSongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSongButtonActionPerformed
        new AddSong(c).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addSongButtonActionPerformed

    private void deleteSongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSongButtonActionPerformed
        String name;
        try{
            name=songList.getModel().getValueAt(songList.getSelectedRow(),0).toString();
            db.deleteSong(name);
        }catch(ArrayIndexOutOfBoundsException e)
        {
            JOptionPane.showMessageDialog(AllSongs.this, "No songs in the system!");
            return;
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(AllSongs.this, "Please try again!");
            return;
        }
        JOptionPane.showMessageDialog(AllSongs.this, "Successfully deleted from the system: "+name);
        new AllSongs().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_deleteSongButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllSongs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllSongs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllSongs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllSongs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllSongs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSongButton;
    private javax.swing.JButton addplaylistButton;
    private javax.swing.JButton deleteSongButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainmenuButton;
    private javax.swing.JTable songList;
    // End of variables declaration//GEN-END:variables
}
